# Generated by Django 5.0.6 on 2024-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
