# Generated by Django 5.0.6 on 2024-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipmenttracking_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttracking',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
